---
version: 2

multi-ecosystem-groups:
  daily:
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
      prefix-development: chore(dev-deps)
    schedule:
      interval: daily

updates:
  - directory: /
    package-ecosystem: pip
    patterns: ['*']
    rebase-strategy: auto
    multi-ecosystem-group: daily

  - directory: /
    package-ecosystem: uv
    patterns: ['*']
    rebase-strategy: auto
    multi-ecosystem-group: daily

  - directory: /
    multi-ecosystem-group: daily
    package-ecosystem: cargo
    patterns: ['*']
    rebase-strategy: auto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
