version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - git fetch --unshallow || true
    - pip3 install --upgrade pip poetry
    - poetry self add 'poethepoet[poetry_plugin]'
    - poetry setup-versioning
    - poetry install --all-extras
    - poetry docs
    - mkdir -p _readthedocs/html
    - cp --recursive docs/* _readthedocs/html/
