include = ["**/*.toml", "*.lock"]

[formatting]
align_entries         = true
array_auto_collapse   = true
array_auto_expand     = true
column_width          = 120
reorder_arrays        = true
reorder_inline_tables = true
reorder_keys          = true
