name: cargo
description: Run `cargo` commands for this project
inputs:
  command:
    description: The `cargo` command to run

runs:
  steps:
    - run: cargo ${{ inputs.command }}
      shell: sh

  using: composite
