# Run this workflow to test Python code changes.
name: 🎨 poetry (PR)

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry
        with:
          command: lint
          groups: main,build,test,lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cargo
        with:
          command: install dicom-storescp

      - uses: ./.github/actions/poetry
        with:
          command: test --error-for-skips
          groups: main,build,test
          python-version: ${{ matrix.py }}

      - if: always()
        name: Upload coverage reports to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
